CREATE TABLE [dbo].[tblElements]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [name] NCHAR(50) NOT NULL, 
	[creationDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [modificationDate] DATETIME NOT NULL DEFAULT GETDATE() 
)
